POST localhost:8080/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmR1bGF6aXpvdm90YWJlazc0MDVAZ21haWwuY29tIiwicm9sZXMiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImlkIjoiOTQiLCJpYXQiOjE3MzU5NzQwMjksImV4cCI6MTczNjA2MDQyOX0.Bk7fOEgbmHc2of1jgrj9V-m9s5iuaENBH1qgwFbceapjMLYPthx5C_IO0rKQZbdi8xsBZ3ZC0GDBN63BS_hK2Q
