POST localhost:8080/api/attaches/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTg5MTQ4Mjc3NzgiLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMTE1IiwiaWF0IjoxNzM4NjU5Mjk5LCJleHAiOjE3Mzg3NDU2OTl9.odhbUp332Kf1fJ1eisqT0ePPpPct9cCGcx1U5fbN2Cn3cyacHG_2DJye-WTrmYm4yfcu1lBl0sgaH3M0UYh-RQ

--WebAppBoundary
Content-Disposition: form-data; name="multipartFile"; filename="444.png"

<C:\Users\oabdulazizov\Downloads\Telegram Desktop\Новая папка\444.png

