GET localhost:8080/api/profiles
Content-Type: application/json


{
  "name": "ali",
  "password": "12345",
  "visible": true,
  "status": "ACTIVE",
  "username": "+998937877405"
}

###
POST localhost:8080/api/profile-roles
Content-Type: application/json

{
  "profileId": 1,
  "roles": "ROLE_USER"
}

###
POST http://localhost:8080/api/auths/login
Content-Type: application/json
Accept-Language: EN

{
  "username": "998914827778",
  "password": "12345"
}

### reset password
POST localhost:8080/api/auths/reset-password
Content-Type: application/json

{
  "username": "abdulazizovotabek7405@gmail.com"
}

###
POST localhost:8080/api/auths/reset-password-confirm
Content-Type: application/json

{
  "username": "abdulazizovotabek7405@gmail.com",
  "configCode": "16626",
  "password": "66666"
}

###
POST localhost:8080/api/auths/registration
Content-Type: application/json
Accept-Language: RU

{
  "name": "otabek",
  "username": "998937877405",
  "password": "12345"
}

###
POST localhost:8080/api/auths/registration/sms-verification
Content-Type: application/json

{
  "phone": "998937877405",
  "code": "This is test from Eskiz"
}

###

POST localhost:8080/api/auths/registration/sms-verification-resend
Content-Type: application/json
Accept-Language: RU

{
  "phone": "998937877405"
}

####
POST localhost:8080/api/auths/login
Content-Type: application/json

{
  "username": "admin@gmail.com",
  "password": "123456"
}

###
GET localhost:8080/api/profiles/

