POST localhost:8080/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmR1bGF6aXpvdm90YWJlazc0MDVAZ21haWwuY29tIiwicm9sZXMiOiJVU0VSIiwiaWQiOiIxIiwiaWF0IjoxNzQxMzI0OTYyLCJleHAiOjE3NDE0MTEzNjJ9.mSv3w4UaJSASIIEAsMvQaLoHJDo2m8LEumFoumBSAAPC4Snb4rJOcno1cw3V0p66yw-I1e4hBlthQmYiXSu-7A

{
  "title": "uzkassa",
  "content": "erjgberjhgbjrhebgljwrebgljwbtgjlbljrtbljrwbgljrtglkj",
  "photo": {
    "id": "ff675bd0-87ec-4f75-aae8-c743be7468ec.png"
  }
}
###
POST localhost:8080/api/posts/public/filter
Content-Type: application/json

{
  "query": null,
  "exceptId": "2446137a-1964-4466-95d0-2e5878386a19.png"
}
###
GET localhost:8080/api/attaches/ff675bd0-87ec-4f75-aae8-c743be7468ec.png