PUT localhost:8080/api/profiles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmR1bGF6aXpvdm90YWJlazc0MDVAZ21haWwuY29tIiwicm9sZXMiOiJST0xFX1VTRVIiLCJpZCI6IjEwNSIsImlhdCI6MTczNzYyMzI1NiwiZXhwIjoxNzM3NzA5NjU2fQ.Yia7FLeRfcJsT7uy9yAKfWgDzhpINEX8OnWe5XLWTa4snhbBzCMqkPs_QJJvJHDAdOKaXn5YMG27L2EW7cyflQ

{
  "name": "otabek"
}

###
PUT localhost:8080/api/profiles/update-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmR1bGF6aXpvdm90YWJlazc0MDVAZ21haWwuY29tIiwicm9sZXMiOiJST0xFX1VTRVIiLCJpZCI6IjEwNSIsImlhdCI6MTczNzYyODE5MCwiZXhwIjoxNzM3NzE0NTkwfQ.YjSKViK-Unz9mcl5pouzK4pJz3o8wPf1hGQrbpQVOEbUPcFLwLiREzpw5Uvt9b-73i5fZKKVCOHA6dwIch2GDg

{
  "oldPassword": "66666",
  "newPassword": "11111"
}
###
PUT localhost:8080/api/profiles/update-username
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmR1bGF6aXpvdm90YWJlazc0MDU1QGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiIxMDUiLCJpYXQiOjE3Mzc3MTMyNTcsImV4cCI6MTczNzc5OTY1N30.vkNVRIrMlVcPymRm9nbOaiQOpAtH-RJ9DYvsag_yjO_8Z2nnZVahD43c8tNswI-4_i-Y3fOb0P3IcnJgNUbBTQ

{
  "username": "998937877405"
}