GET localhost:8080/api/profiles
Content-Type: application/json


{
  "name": "ali",
  "password": "12345",
  "visible": true,
  "status": "ACTIVE",
  "username": "+998937877405"
}

###
POST localhost:8080/api/profile-roles
Content-Type: application/json

{
  "profileId": 1,
  "roles": "ROLE_USER"
}

###
POST http://localhost:8080/api/auths/login
Accept-Language: EN
Content-Type: application/json
Accept-Language: RU

{
  "username": "abdulazizovotabek7405@gmail.com",
  "password": "12345"
}

###
POST localhost:8080/api/auths/registration
Content-Type: application/json
Accept-Language: RU

{
  "name": "otabek",
  "username": "998937877405",
  "password": "12345"
}

###
POST localhost:8080/api/auths/registration/sms-verification
Content-Type: application/json

{
  "phone": "998937877405",
  "code": "This is test from Eskiz"
}

####
GET http://localhost:8080/api/auths/registration/verification/eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OCIsImlhdCI6MTczNTk5MDg1MiwiZXhwIjoxNzM1OTkxMjEyfQ.islkXeNPMmikFyELnQa8iiSP6axCBIQqmXtQiE6bfVwP5PQaucFeVmO2fQ9YWQN2XgEzdZ-tc3mDYFPrLCZqIA
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7